name: Post commits to Discord

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for diffs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Discord embed
        id: build
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          ACTOR="${{ github.actor }}"
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          COMMITS=$(jq -r '.commits[] | "- [`\(.id[0:7])`](\(.url)) \(.message | gsub("\\n"; " ")) by \(.author.username // .author.name)"' "$GITHUB_EVENT_PATH" || true)

          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE" ]; then
            CHANGES=$(git diff --name-status "$AFTER^!" | head -n 20 || true)
          else
            CHANGES=$(git diff --name-status "$BEFORE" "$AFTER" | head -n 20 || true)
          fi

          cat > payload.json <<JSON
          {
            "embeds": [
              {
                "title": "Push to ${REPO}:${BRANCH}",
                "url": "https://github.com/${REPO}/compare/${BEFORE}...${AFTER}",
                "description": "Pushed by **${ACTOR}**",
                "color": 9041788,
                "fields": [
                  {
                    "name": "Commits",
                    "value": "${COMMITS:-No commits found}",
                    "inline": false
                  },
                  {
                    "name": "Changed files",
                    "value": "```\\n${CHANGES:-No changes}\\n```",
                    "inline": false
                  }
                ]
              }
            ]
          }
          JSON
          echo "payload=payload.json" >> "$GITHUB_OUTPUT"

      - name: Send to Discord
        run: |
          curl -sS -H "Content-Type: application/json" \
            -d @"${{ steps.build.outputs.payload }}" \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
